version: "3.7"
services:
  s3:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
      DEFAULT_REGSION: ap-northeast-1
      DATA_DIR: /tmp/localstack/data
    volumes:
      - ./localstack:/tmp/localstack
    ports:
      - 4566:4566