// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type User struct {
	ent.Schema
}

func (User) Fields() []ent.Field {
	return []ent.Field{field.String("id").Comment("ID"), field.String("name").Comment("名前"), field.String("email").Unique(), field.Enum("role").Comment("権限").Values("admin", "user"), field.Time("deleted_at").Optional(), field.Time("registered_at"), field.Time("modified_at"), field.Time("created_at"), field.Time("updated_at")}
}
func (User) Edges() []ent.Edge {
	return []ent.Edge{edge.To("groups", Group.Type)}
}
func (User) Annotations() []schema.Annotation {
	return nil
}
